### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/stuffthingmaps_detectron2/train2017_base_label_count.json'

### ISSUE THREAD

**Issue by vamsikrishna7909** [MendelXu/zsseg.baseline#29]
when I use this command : `python train_net.py --config-file configs/coco-stuff-164k-156/zero_shot_proposal_classification_learn_prompt_bs32_10k.yaml --num-gpus 2` for training with learned prompts. It is giving me below issue. where do I get train2017_base_label_count.json file. I don't see it in detectron2 folder. Please check below

```
W1104 22:16:58.190389 134318642562880 torch/multiprocessing/spawn.py:146] Terminating process 30171 via signal SIGTERM
Traceback (most recent call last):
  File "train_net.py", line 336, in <module>
    launch(
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/vamsi_project/zsseg_repo/zsseg.baseline/train_net.py", line 328, in main
    trainer = Trainer(cfg)
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/vamsi_project/zsseg_repo/zsseg.baseline/train_net.py", line 127, in build_train_loader
    dataset = dataset_sample_per_class(cfg)
  File "/vamsi_project/zsseg_repo/zsseg.baseline/mask_former/data/build.py", line 344, in dataset_sample_per_class
    dataset_dicts = get_detection_dataset_dicts(
  File "/vamsi_project/zsseg_repo/zsseg.baseline/mask_former/data/build.py", line 124, in get_detection_dataset_dicts
    dataset_dicts = [
  File "/vamsi_project/zsseg_repo/zsseg.baseline/mask_former/data/build.py", line 125, in <listcomp>
    wrap_metas(DatasetCatalog.get(dataset_name), dataset_name=dataset_name)
  File "/opt/conda/envs/zsseg_det_env/lib/python3.8/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/vamsi_project/zsseg_repo/zsseg.baseline/mask_former/data/datasets/register_coco_stuff.py", line 329, in <lambda>
    lambda x=image_dir, y=gt_dir: load_binary_mask(
  File "/vamsi_project/zsseg_repo/zsseg.baseline/mask_former/data/datasets/utils.py", line 23, in load_binary_mask
    with open(label_count_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/stuffthingmaps_detectron2/train2017_base_label_count.json'

(zsseg_det_env) zsseg_repo/zsseg.baseline# ls
LICENSE  README.md  configs  datasets  mask_former  output  requirements.txt  resources  third_party  tools  train_net.py  wandb
(zsseg_det_env) zsseg_repo/zsseg.baseline# cd datasets/coco/stuffthingmaps_detectron2/
(zsseg_det_env) zsseg_repo/zsseg.baseline/datasets/coco/stuffthingmaps_detectron2# ls
test2017  train2017  train2017_base  train2017_base_label_count.pkl  train2017_novel  val2017  val2017_base  val2017_label_count.pkl  val2017_novel
```

**Comment by vamsikrishna7909** [comment]
I had to change the file from .pk1 to .json
