### ISSUE TITLE
Something unexpected

### ISSUE THREAD

**Issue by NickChang97** [MendelXu/zsseg.baseline#3]
Hi,thanks for sharing your codes. According to the doc, `python datasets/prepare_coco_stuff_164k_sem_seg.py datasets/coco` I get this error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "datasets/prepare_coco_stuff_164k_sem_seg.py", line 209, in convert_to_trainID
    Image.fromarray(mask_copy).save(seg_filename, "PNG")
  File "/home/qing_chang/env_detetron2/lib/python3.7/site-packages/PIL/Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/stuffthingmaps_detectron2/val2017/000000263425.png'

**Comment by AnukritiSinghh** [comment]
Change [this](https://github.com/MendelXu/zsseg.baseline/blob/bb6504aa8b573de1afa7f58c8e5d40de524f0a58/datasets/prepare_coco_stuff_164k_sem_seg.py#L234) line to val2017. It might work then.

**Comment by NickChang97** [comment]
Thanks a lot, I will try it.
