### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOC2012/annotations_detectron2/train_base_10class/2007_000032.png'

### ISSUE THREAD

**Issue by haohao333** [MendelXu/zsseg.baseline#31]
(pytorch) root@autodl-container-b537459424-eba7a9d0:~/test/zsseg.baseline-master# python datasets/prepare_voc_sem_seg.py datasets/VOC2012
{0: 255, 1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19, 255: 255}
{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14}
{16: 0, 17: 1, 18: 2, 19: 3, 20: 4}
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 10582/10582, 1125.9 task/s, elapsed: 9s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1449/1449, 1157.9 task/s, elapsed: 1s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 10582/10582, 1181.7 task/s, elapsed: 9s, ETA:     0s
[                                                  ] 0/10582, elapsed: 0s, ETA:multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/test/zsseg.baseline-master/datasets/prepare_voc_sem_seg.py", line 58, in convert_to_trainID
    Image.fromarray(mask_copy).save(seg_filename, "PNG")
  File "/root/miniconda3/envs/pytorch/lib/python3.9/site-packages/PIL/Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOC2012/annotations_detectron2/train_base_10class/2007_000032.png'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/test/zsseg.baseline-master/datasets/prepare_voc_sem_seg.py", line 212, in <module>
    main()
  File "/root/test/zsseg.baseline-master/datasets/prepare_voc_sem_seg.py", line 126, in main
    mmcv.track_parallel_progress(
  File "/root/miniconda3/envs/pytorch/lib/python3.9/site-packages/mmcv/utils/progressbar.py", line 164, in track_parallel_progress
    for result in gen:
  File "/root/miniconda3/envs/pytorch/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOC2012/annotations_detectron2/train_base_10class/2007_000032.png'
(pytorch) root@autodl-container-b537459424-eba7a9d0:~/test/zsseg.baseline-master# 
when i use  python datasets/prepare_voc_sem_seg.py datasets/VOC2012  
i find this problem,can any one can solve this problem?

**Comment by vamsikrishna7909** [comment]
you can manually create the folder "train_base_10class", or you can update the code which is in "prepare_voc_sem_seg.py" with same name that is expecting.

**Comment by vamsikrishna7909** [comment]
https://github.com/MendelXu/zsseg.baseline/issues/25
https://github.com/MendelXu/zsseg.baseline/issues/28

similar issues
